package com.pj.oil.gasStation;

import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

@Component
public class AreaRegistry {

    private final Map<String, String> areaMap = new HashMap<>();
    private String[] areaCodes;

    @PostConstruct
    public void init() {
        areaMap.put("01", "서울");
        areaMap.put("02", "경기");
        areaMap.put("03", "강원");
        areaMap.put("04", "충북");
        areaMap.put("05", "충남");
        areaMap.put("06", "전북");
        areaMap.put("07", "전남");
        areaMap.put("08", "경북");
        areaMap.put("09", "경남");
        areaMap.put("10", "부산");
        areaMap.put("11", "제주");
        areaMap.put("14", "대구");
        areaMap.put("15", "인천");
        areaMap.put("16", "광주");
        areaMap.put("17", "대전");
        areaMap.put("18", "울산");
        areaMap.put("19", "세종");
        areaMap.put("0101", "서울 종로구");
        areaMap.put("0102", "서울 중구");
        areaMap.put("0103", "서울 동대문구");
        areaMap.put("0104", "서울 성동구");
        areaMap.put("0105", "서울 성북구");
        areaMap.put("0106", "서울 도봉구");
        areaMap.put("0107", "서울 서대문구");
        areaMap.put("0108", "서울 은평구");
        areaMap.put("0109", "서울 마포구");
        areaMap.put("0110", "서울 용산구");
        areaMap.put("0111", "서울 영등포구");
        areaMap.put("0112", "서울 동작구");
        areaMap.put("0113", "서울 강남구");
        areaMap.put("0114", "서울 강동구");
        areaMap.put("0115", "서울 강서구");
        areaMap.put("0116", "서울 구로구");
        areaMap.put("0117", "서울 관악구");
        areaMap.put("0118", "서울 노원구");
        areaMap.put("0119", "서울 양천구");
        areaMap.put("0120", "서울 중랑구");
        areaMap.put("0121", "서울 서초구");
        areaMap.put("0122", "서울 송파구");
        areaMap.put("0123", "서울 광진구");
        areaMap.put("0124", "서울 강북구");
        areaMap.put("0125", "서울 금천구");
        areaMap.put("0201", "경기 수원시");
        areaMap.put("0202", "경기 성남시");
        areaMap.put("0203", "경기 의정부시");
        areaMap.put("0204", "경기 안양시");
        areaMap.put("0205", "경기 부천시");
        areaMap.put("0206", "경기 동두천시");
        areaMap.put("0207", "경기 광명시");
        areaMap.put("0208", "경기 이천시");
        areaMap.put("0209", "경기 평택시");
        areaMap.put("0210", "경기 구리시");
        areaMap.put("0211", "경기 과천시");
        areaMap.put("0212", "경기 안산시");
        areaMap.put("0213", "경기 오산시");
        areaMap.put("0214", "경기 의왕시");
        areaMap.put("0215", "경기 군포시");
        areaMap.put("0216", "경기 시흥시");
        areaMap.put("0217", "경기 남양주시");
        areaMap.put("0218", "경기 하남시");
        areaMap.put("0219", "경기 고양시");
        areaMap.put("0220", "경기 용인시");
        areaMap.put("0221", "경기 양주시");
        areaMap.put("0222", "경기 여주시");
        areaMap.put("0224", "경기 화성시");
        areaMap.put("0226", "경기 파주시");
        areaMap.put("0228", "경기 광주시");
        areaMap.put("0229", "경기 연천군");
        areaMap.put("0230", "경기 포천시");
        areaMap.put("0231", "경기 가평군");
        areaMap.put("0232", "경기 양평군");
        areaMap.put("0235", "경기 안성시");
        areaMap.put("0236", "경기 김포시");
        areaMap.put("0301", "강원 춘천시");
        areaMap.put("0302", "강원 원주시");
        areaMap.put("0303", "강원 강릉시");
        areaMap.put("0304", "강원 속초시");
        areaMap.put("0305", "강원 동해시");
        areaMap.put("0306", "강원 태백시");
        areaMap.put("0307", "강원 삼척시");
        areaMap.put("0322", "강원 홍천군");
        areaMap.put("0323", "강원 횡성군");
        areaMap.put("0325", "강원 영월군");
        areaMap.put("0326", "강원 평창군");
        areaMap.put("0327", "강원 정선군");
        areaMap.put("0328", "강원 철원군");
        areaMap.put("0329", "강원 화천군");
        areaMap.put("0330", "강원 양구군");
        areaMap.put("0331", "강원 인제군");
        areaMap.put("0332", "강원 고성군");
        areaMap.put("0333", "강원 양양군");
        areaMap.put("0401", "충북 청주시");
        areaMap.put("0402", "충북 충주시");
        areaMap.put("0403", "충북 제천시");
        areaMap.put("0422", "충북 보은군");
        areaMap.put("0423", "충북 옥천군");
        areaMap.put("0424", "충북 영동군");
        areaMap.put("0425", "충북 진천군");
        areaMap.put("0426", "충북 괴산군");
        areaMap.put("0427", "충북 음성군");
        areaMap.put("0430", "충북 단양군");
        areaMap.put("0431", "충북 증평군");
        areaMap.put("0502", "충남 천안시");
        areaMap.put("0503", "충남 공주시");
        areaMap.put("0504", "충남 아산시");
        areaMap.put("0505", "충남 보령시");
        areaMap.put("0506", "충남 서산시");
        areaMap.put("0507", "충남 논산시");
        areaMap.put("0508", "충남 계룡시");
        areaMap.put("0521", "충남 금산군");
        areaMap.put("0526", "충남 부여군");
        areaMap.put("0527", "충남 서천군");
        areaMap.put("0529", "충남 청양군");
        areaMap.put("0530", "충남 홍성군");
        areaMap.put("0531", "충남 예산군");
        areaMap.put("0533", "충남 당진시");
        areaMap.put("0537", "충남 태안군");
        areaMap.put("0601", "전북 전주시");
        areaMap.put("0602", "전북 군산시");
        areaMap.put("0603", "전북 익산시");
        areaMap.put("0604", "전북 남원시");
        areaMap.put("0605", "전북 정읍시");
        areaMap.put("0606", "전북 김제시");
        areaMap.put("0621", "전북 완주군");
        areaMap.put("0622", "전북 진안군");
        areaMap.put("0623", "전북 무주군");
        areaMap.put("0624", "전북 장수군");
        areaMap.put("0625", "전북 임실군");
        areaMap.put("0627", "전북 순창군");
        areaMap.put("0629", "전북 고창군");
        areaMap.put("0630", "전북 부안군");
        areaMap.put("0702", "전남 목포시");
        areaMap.put("0703", "전남 여수시");
        areaMap.put("0704", "전남 순천시");
        areaMap.put("0705", "전남 나주시");
        areaMap.put("0707", "전남 광양시");
        areaMap.put("0722", "전남 담양군");
        areaMap.put("0723", "전남 곡성군");
        areaMap.put("0724", "전남 구례군");
        areaMap.put("0728", "전남 고흥군");
        areaMap.put("0729", "전남 보성군");
        areaMap.put("0730", "전남 화순군");
        areaMap.put("0731", "전남 장흥군");
        areaMap.put("0732", "전남 강진군");
        areaMap.put("0733", "전남 해남군");
        areaMap.put("0734", "전남 영암군");
        areaMap.put("0735", "전남 무안군");
        areaMap.put("0737", "전남 함평군");
        areaMap.put("0738", "전남 영광군");
        areaMap.put("0739", "전남 장성군");
        areaMap.put("0740", "전남 완도군");
        areaMap.put("0741", "전남 진도군");
        areaMap.put("0742", "전남 신안군");
        areaMap.put("0801", "경북 포항시");
        areaMap.put("0802", "경북 경주시");
        areaMap.put("0803", "경북 김천시");
        areaMap.put("0804", "경북 영주시");
        areaMap.put("0805", "경북 영천시");
        areaMap.put("0806", "경북 안동시");
        areaMap.put("0807", "경북 구미시");
        areaMap.put("0808", "경북 문경시");
        areaMap.put("0809", "경북 상주시");
        areaMap.put("0810", "경북 경산시");
        areaMap.put("0823", "경북 의성군");
        areaMap.put("0825", "경북 청송군");
        areaMap.put("0826", "경북 영양군");
        areaMap.put("0827", "경북 영덕군");
        areaMap.put("0832", "경북 청도군");
        areaMap.put("0833", "경북 고령군");
        areaMap.put("0834", "경북 성주군");
        areaMap.put("0835", "경북 칠곡군");
        areaMap.put("0840", "경북 예천군");
        areaMap.put("0842", "경북 봉화군");
        areaMap.put("0843", "경북 울진군");
        areaMap.put("0844", "경북 울릉군");
        areaMap.put("0902", "경남 창원시");
        areaMap.put("0904", "경남 진주시");
        areaMap.put("0906", "경남 통영시");
        areaMap.put("0907", "경남 사천시");
        areaMap.put("0908", "경남 김해시");
        areaMap.put("0909", "경남 밀양시");
        areaMap.put("0910", "경남 거제시");
        areaMap.put("0911", "경남 양산시");
        areaMap.put("0922", "경남 의령군");
        areaMap.put("0923", "경남 함안군");
        areaMap.put("0924", "경남 창녕군");
        areaMap.put("0932", "경남 고성군");
        areaMap.put("0934", "경남 남해군");
        areaMap.put("0935", "경남 하동군");
        areaMap.put("0936", "경남 산청군");
        areaMap.put("0937", "경남 함양군");
        areaMap.put("0938", "경남 거창군");
        areaMap.put("0939", "경남 합천군");
        areaMap.put("1001", "부산 중구");
        areaMap.put("1002", "부산 서구");
        areaMap.put("1003", "부산 동구");
        areaMap.put("1004", "부산 영도구");
        areaMap.put("1005", "부산 부산진구");
        areaMap.put("1006", "부산 동래구");
        areaMap.put("1007", "부산 남구");
        areaMap.put("1008", "부산 북구");
        areaMap.put("1009", "부산 해운대구");
        areaMap.put("1010", "부산 사하구");
        areaMap.put("1011", "부산 강서구");
        areaMap.put("1012", "부산 금정구");
        areaMap.put("1013", "부산 연제구");
        areaMap.put("1014", "부산 수영구");
        areaMap.put("1015", "부산 사상구");
        areaMap.put("1031", "부산 기장군");
        areaMap.put("1101", "제주 제주시");
        areaMap.put("1102", "제주 서귀포시");
        areaMap.put("1401", "대구 중구");
        areaMap.put("1402", "대구 동구");
        areaMap.put("1403", "대구 서구");
        areaMap.put("1404", "대구 남구");
        areaMap.put("1405", "대구 북구");
        areaMap.put("1406", "대구 수성구");
        areaMap.put("1407", "대구 달서구");
        areaMap.put("1431", "대구 달성군");
        areaMap.put("1432", "대구 군위군");
        areaMap.put("1501", "인천 중구");
        areaMap.put("1502", "인천 동구");
        areaMap.put("1503", "인천 미추홀구");
        areaMap.put("1504", "인천 부평구");
        areaMap.put("1505", "인천 서구");
        areaMap.put("1506", "인천 남동구");
        areaMap.put("1507", "인천 연수구");
        areaMap.put("1508", "인천 계양구");
        areaMap.put("1531", "인천 강화군");
        areaMap.put("1532", "인천 옹진군");
        areaMap.put("1601", "광주 동구");
        areaMap.put("1602", "광주 서구");
        areaMap.put("1603", "광주 북구");
        areaMap.put("1604", "광주 광산구");
        areaMap.put("1605", "광주 남구");
        areaMap.put("1701", "대전 동구");
        areaMap.put("1702", "대전 중구");
        areaMap.put("1703", "대전 서구");
        areaMap.put("1704", "대전 유성구");
        areaMap.put("1705", "대전 대덕구");
        areaMap.put("1801", "울산 중구");
        areaMap.put("1802", "울산 남구");
        areaMap.put("1803", "울산 동구");
        areaMap.put("1804", "울산 북구");
        areaMap.put("1831", "울산 울주군");
        areaMap.put("1901", "세종시");
        initializeAreaCodes();
    }

    private void initializeAreaCodes() {
        areaCodes = areaMap.keySet().toArray(new String[0]);
    }

    public Map<String, String> getAreaMap() {
        return Collections.unmodifiableMap(areaMap);
    }

    public String[] getAreaCodes() {
        return areaCodes.clone(); // 배열의 불변성을 유지하기 위해 복사본 반환
    }

    public String getAreaName(String code) {
        return areaMap.getOrDefault(code, "기타");
    }
}
